import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Haptics from "expo-haptics";
import { router } from "expo-router";
import { useEffect,useState } from "react";
import { Pressable,ScrollView,StyleSheet,Text,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { lessons } from "@/lib/academy";
const KEY="chess-universe-academy-complete-v1";
export default function Academy(){const [complete,setComplete]=useState<string[]>([]);const [open,setOpen]=useState<string|null>(null);useEffect(()=>{AsyncStorage.getItem(KEY).then(v=>v&&setComplete(JSON.parse(v))).catch(()=>{})},[]);const finish=async(id:string)=>{const next=complete.includes(id)?complete:[...complete,id];setComplete(next);await AsyncStorage.setItem(KEY,JSON.stringify(next));void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Universe</Text></Pressable><Text style={s.eyebrow}>LEARN</Text><Text style={s.title}>Academy</Text><Text style={s.intro}>{complete.length}/{lessons.length} lessons complete · Progress saves on this device now and can sync to your account once signed in.</Text><View style={s.progress}><View style={[s.progressFill,{width:`${(complete.length/lessons.length)*100}%`}]} /></View>{lessons.map((lesson,i)=>{const done=complete.includes(lesson.id);const expanded=open===lesson.id;return <View key={lesson.id} style={s.card}><Pressable onPress={()=>setOpen(expanded?null:lesson.id)}><View style={s.row}><Text style={s.track}>{lesson.track} · {i+1}</Text><Text style={done?s.done:s.chevron}>{done?"✓":"⌄"}</Text></View><Text style={s.lessonTitle}>{lesson.title}</Text><Text style={s.summary}>{lesson.summary}</Text></Pressable>{expanded&&<View style={s.lessonBody}><Text style={s.body}>{lesson.body}</Text><View style={s.checkpoint}><Text style={s.checkLabel}>BOARD CHECK</Text><Text style={s.checkText}>{lesson.checkpoint}</Text></View><Pressable style={[s.finish,done&&s.finished]} onPress={()=>finish(lesson.id)}><Text style={s.finishText}>{done?"Completed ✓":"Mark lesson complete"}</Text></Pressable></View>}</View>})}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0b0e0f"},content:{padding:22,paddingBottom:44},back:{color:"#9ca7a3",fontSize:15,fontWeight:"700",marginTop:8},eyebrow:{color:"#d7ff4a",fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:32},title:{color:"#f5f7f0",fontSize:39,fontWeight:"900",letterSpacing:-1.4,marginTop:5},intro:{color:"#929d99",fontSize:14,lineHeight:21,marginTop:8},progress:{height:6,backgroundColor:"#202827",borderRadius:4,overflow:"hidden",marginTop:18,marginBottom:18},progressFill:{height:"100%",backgroundColor:"#d7ff4a"},card:{backgroundColor:"#151a1b",borderRadius:20,padding:18,borderWidth:1,borderColor:"#273031",marginBottom:11},row:{flexDirection:"row",justifyContent:"space-between"},track:{color:"#d7ff4a",fontSize:9,fontWeight:"900",letterSpacing:1.5},done:{color:"#d7ff4a",fontSize:16,fontWeight:"900"},chevron:{color:"#6e7a76",fontSize:17},lessonTitle:{color:"#f5f7f0",fontSize:21,fontWeight:"900",marginTop:12},summary:{color:"#87938e",fontSize:13,marginTop:5},lessonBody:{borderTopWidth:1,borderTopColor:"#273031",marginTop:16,paddingTop:16},body:{color:"#c5ccc8",fontSize:14,lineHeight:22},checkpoint:{backgroundColor:"#0f1415",borderRadius:14,padding:14,marginTop:15},checkLabel:{color:"#d7ff4a",fontSize:9,fontWeight:"900",letterSpacing:1.5},checkText:{color:"#e3e7e1",fontSize:13,lineHeight:19,marginTop:5},finish:{backgroundColor:"#d7ff4a",borderRadius:13,padding:13,alignItems:"center",marginTop:13},finished:{backgroundColor:"#28312a"},finishText:{color:"#0b0e0f",fontSize:13,fontWeight:"900"}});
