import { router } from "expo-router";
import { useEffect,useState } from "react";
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { isSupabaseConfigured,supabase } from "@/lib/supabase";
import { useSession } from "@/lib/session";
type Mode="signin"|"signup"|"forgot";type Profile={username:string;rating:number;wins:number;losses:number;draws:number};
export default function Account(){const {session,loading}=useSession();const [mode,setMode]=useState<Mode>("signin");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [username,setUsername]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [profile,setProfile]=useState<Profile|null>(null);
useEffect(()=>{if(!supabase||!session){setProfile(null);return}void supabase.from("profiles").select("username,rating,wins,losses,draws").eq("id",session.user.id).single().then(({data})=>setProfile(data as Profile|null))},[session?.user.id]);
const submit=async()=>{if(!supabase)return;setBusy(true);setMessage("");if(mode==="forgot"){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:"chessuniverse://account"});setMessage(error?.message??"If that email belongs to an account, check your inbox.");setBusy(false);return}if(mode==="signup"){const {error}=await supabase.auth.signUp({email,password,options:{data:{username},emailRedirectTo:"chessuniverse://account"}});setMessage(error?.message??"Account created. Check your email if confirmation is enabled.");setBusy(false);return}const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?.message??"Signed in.");setBusy(false)};
if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator color="#d7ff4a" style={{marginTop:80}}/></SafeAreaView>;
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Universe</Text></Pressable><Text style={s.eyebrow}>ACCOUNT</Text>{!isSupabaseConfigured||!supabase?<View style={s.card}><Text style={s.title}>Connection ready</Text><Text style={s.muted}>Add the existing Chess Universe Supabase URL and publishable key to the Expo environment before the first device build.</Text></View>:session?<View style={s.card}><Text style={s.title}>{profile?.username??session.user.user_metadata.username??"Player"}</Text><Text style={s.email}>{session.user.email}</Text>{profile&&<><Text style={s.rating}>{profile.rating}</Text><Text style={s.ratingLabel}>RATING</Text><View style={s.stats}><Stat n={profile.wins} label="Wins"/><Stat n={profile.losses} label="Losses"/><Stat n={profile.draws} label="Draws"/></View></>}<Pressable style={s.secondary} onPress={()=>void supabase.auth.signOut()}><Text style={s.secondaryText}>Sign out</Text></Pressable></View>:<View style={s.card}><Text style={s.title}>{mode==="signin"?"Welcome back":mode==="signup"?"Join Chess Universe":"Reset password"}</Text>{mode==="signup"&&<TextInput value={username} onChangeText={setUsername} placeholder="Username" placeholderTextColor="#697570" autoCapitalize="none" style={s.input}/>}<TextInput value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor="#697570" keyboardType="email-address" autoCapitalize="none" style={s.input}/>{mode!=="forgot"&&<TextInput value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor="#697570" secureTextEntry style={s.input}/>}<Pressable disabled={busy} style={s.primary} onPress={()=>void submit()}><Text style={s.primaryText}>{busy?"Working…":mode==="signin"?"Sign in":mode==="signup"?"Create account":"Send recovery link"}</Text></Pressable>{message?<Text style={s.message}>{message}</Text>:null}<View style={s.links}>{mode==="signin"?<><Pressable onPress={()=>setMode("forgot")}><Text style={s.link}>Forgot password?</Text></Pressable><Pressable onPress={()=>setMode("signup")}><Text style={s.link}>Need an account? Sign up</Text></Pressable></>:<Pressable onPress={()=>setMode("signin")}><Text style={s.link}>Back to sign in</Text></Pressable>}</View></View>}</ScrollView></SafeAreaView>}
function Stat({n,label}:{n:number;label:string}){return <View style={s.stat}><Text style={s.statN}>{n}</Text><Text style={s.statLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0b0e0f"},content:{padding:22,paddingBottom:44},back:{color:"#9ca7a3",fontSize:15,fontWeight:"700",marginTop:8},eyebrow:{color:"#d7ff4a",fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:34,marginBottom:10},card:{backgroundColor:"#151a1b",borderWidth:1,borderColor:"#273031",borderRadius:24,padding:20},title:{color:"#f5f7f0",fontSize:28,fontWeight:"900"},muted:{color:"#909b97",fontSize:14,lineHeight:21,marginTop:10},email:{color:"#8d9894",fontSize:13,marginTop:5},rating:{color:"#d7ff4a",fontSize:42,fontWeight:"900",marginTop:22},ratingLabel:{color:"#74807b",fontSize:9,fontWeight:"900",letterSpacing:1.5},stats:{flexDirection:"row",gap:8,marginTop:18},stat:{flex:1,backgroundColor:"#0f1415",borderRadius:14,padding:13},statN:{color:"#f5f7f0",fontSize:20,fontWeight:"900"},statLabel:{color:"#74807b",fontSize:10,marginTop:3},input:{backgroundColor:"#0e1314",borderWidth:1,borderColor:"#2a3433",borderRadius:14,color:"#f5f7f0",padding:15,fontSize:15,marginTop:11},primary:{backgroundColor:"#d7ff4a",borderRadius:14,padding:15,alignItems:"center",marginTop:14},primaryText:{color:"#0b0e0f",fontSize:14,fontWeight:"900"},secondary:{borderWidth:1,borderColor:"#3a4643",borderRadius:14,padding:14,alignItems:"center",marginTop:20},secondaryText:{color:"#f5f7f0",fontSize:13,fontWeight:"800"},message:{color:"#c8d0cc",fontSize:12,lineHeight:18,marginTop:12},links:{gap:12,marginTop:18},link:{color:"#d7ff4a",fontSize:13,fontWeight:"800"}});
