import { router } from "expo-router";
import { useCallback,useEffect,useState } from "react";
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useSession } from "@/lib/session";
import { supabase } from "@/lib/supabase";
type Game={id:string;white_id:string|null;black_id:string|null;status:string;result:string|null;result_reason:string|null;variant:string;created_at:string;ended_at:string|null;time_control_minutes:number;pgn:string};
function result(g:Game,id:string){if(g.status!=="completed")return g.status==="active"?"LIVE":"WAITING";if(g.result==="draw")return"DRAW";if(g.result==="white")return g.white_id===id?"WIN":"LOSS";if(g.result==="black")return g.black_id===id?"WIN":"LOSS";return"COMPLETE"}
export default function Games(){const {session,loading}=useSession();const [games,setGames]=useState<Game[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const load=useCallback(async()=>{if(!supabase||!session)return;setBusy(true);const id=session.user.id;const {data,error}=await supabase.from("games").select("id,white_id,black_id,status,result,result_reason,variant,created_at,ended_at,time_control_minutes,pgn").or(`white_id.eq.${id},black_id.eq.${id}`).order("created_at",{ascending:false}).limit(50);setGames((data??[]) as Game[]);setMessage(error?.message??"");setBusy(false)},[session?.user.id]);useEffect(()=>{void load()},[load]);if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator color="#d7ff4a" style={{marginTop:80}}/></SafeAreaView>;return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()} tintColor="#d7ff4a"/>} contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Universe</Text></Pressable><Text style={s.eyebrow}>REVIEW</Text><Text style={s.title}>My Games</Text><Text style={s.intro}>Your Classic and Battle games from the shared Chess Universe account.</Text>{!session?<View style={s.empty}><Text style={s.emptyTitle}>Sign in to see your games.</Text><Pressable onPress={()=>router.push("/account" as never)} style={s.primary}><Text style={s.primaryText}>Sign in</Text></Pressable></View>:message?<Text style={s.error}>{message}</Text>:games.length===0&&!busy?<View style={s.empty}><Text style={s.emptyTitle}>No games yet.</Text><Text style={s.emptyText}>Online games will appear here automatically.</Text></View>:<View style={s.list}>{games.map(g=><Pressable key={g.id} onPress={()=>router.push({pathname:"/replay/[id]",params:{id:g.id}} as never)} style={s.card}><View style={s.row}><Text style={s.variant}>{g.variant==="battle"?"BATTLE":"CLASSIC"}</Text><Text style={s.result}>{result(g,session.user.id)}</Text></View><Text style={s.date}>{new Date(g.ended_at??g.created_at).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}</Text><Text style={s.meta}>{g.time_control_minutes===0?"Untimed":`${g.time_control_minutes} min`} · {g.result_reason?.replaceAll("_"," ")??"Open game"}</Text><Text style={s.review}>Review game →</Text></Pressable>)}</View>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0b0e0f"},content:{padding:22,paddingBottom:44},back:{color:"#9ca7a3",fontSize:15,fontWeight:"700",marginTop:8},eyebrow:{color:"#d7ff4a",fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:32},title:{color:"#f5f7f0",fontSize:39,fontWeight:"900",letterSpacing:-1.4,marginTop:5},intro:{color:"#929d99",fontSize:14,lineHeight:21,marginTop:8,marginBottom:18},list:{gap:10},card:{backgroundColor:"#151a1b",borderRadius:18,padding:17,borderWidth:1,borderColor:"#273031"},row:{flexDirection:"row",justifyContent:"space-between"},variant:{color:"#d7ff4a",fontSize:9,fontWeight:"900",letterSpacing:1.4},result:{color:"#f5f7f0",fontSize:11,fontWeight:"900"},date:{color:"#f5f7f0",fontSize:18,fontWeight:"900",marginTop:10},meta:{color:"#83908b",fontSize:12,marginTop:5,textTransform:"capitalize"},review:{color:"#d7ff4a",fontSize:12,fontWeight:"800",marginTop:13},empty:{backgroundColor:"#151a1b",borderRadius:20,padding:20},emptyTitle:{color:"#f5f7f0",fontSize:18,fontWeight:"900"},emptyText:{color:"#8b9692",fontSize:13,marginTop:6},primary:{backgroundColor:"#d7ff4a",borderRadius:13,padding:13,alignItems:"center",marginTop:16},primaryText:{color:"#0b0e0f",fontWeight:"900"},error:{color:"#ef9b8f",fontSize:13}});
