import { router } from "expo-router";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,Share,StyleSheet,Text,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useSession } from "@/lib/session";
import { supabase } from "@/lib/supabase";
import { battleFormations } from "@/lib/battle";
import { nativeChallengeUrl,publicChallengeUrl } from "@/lib/deepLinks";
type Game={id:string;white_id:string|null;black_id:string|null;status:string;variant:string;time_control_minutes:number;created_at:string;is_private:boolean;invited_user_id:string|null;battle_formation_key:string|null};
const times=[0,10,15,30];
export default function Online(){const {session,loading}=useSession();const [games,setGames]=useState<Game[]>([]);const [mine,setMine]=useState<Game[]>([]);const [unlocks,setUnlocks]=useState<string[]>([]);const [minutes,setMinutes]=useState(0);const [formation,setFormation]=useState("classic");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const available=useMemo(()=>battleFormations.filter(f=>!f.requires||unlocks.includes(f.requires)),[unlocks]);
const load=useCallback(async()=>{const client=supabase;if(!client||!session)return;setBusy(true);const id=session.user.id;await client.functions.invoke("online-game",{body:{action:"refresh_lobby"}});const select="id,white_id,black_id,status,variant,time_control_minutes,created_at,is_private,invited_user_id,battle_formation_key";const [waiting,myRows,unlockRows]=await Promise.all([client.from("games").select(select).eq("status","waiting").eq("is_private",false).order("created_at",{ascending:false}).limit(60),client.from("games").select(select).in("status",["waiting","active"]).or(`white_id.eq.${id},black_id.eq.${id},invited_user_id.eq.${id}`).order("created_at",{ascending:false}),client.from("player_unlocks").select("reward_key").eq("user_id",id)]);setGames((waiting.data??[]) as Game[]);setMine((myRows.data??[]) as Game[]);setUnlocks((unlockRows.data??[]).map(r=>String(r.reward_key)));setMessage(waiting.error?.message??myRows.error?.message??unlockRows.error?.message??"");setBusy(false)},[session?.user.id]);
useEffect(()=>{void load();const client=supabase;if(!client||!session)return;const ch=client.channel("mobile-lobby").on("postgres_changes",{event:"*",schema:"public",table:"games"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"player_unlocks"},()=>void load()).subscribe();return()=>{void client.removeChannel(ch)}},[load,session?.user.id]);
useEffect(()=>{if(!available.some(f=>f.key===formation))setFormation(available[0]?.key??"classic")},[available,formation]);
const call=async(body:Record<string,unknown>)=>{const client=supabase;if(!client)return null;setBusy(true);setMessage("");const {data,error}=await client.functions.invoke("online-game",{body});if(error){setMessage(error.message);setBusy(false);return null}setBusy(false);return data};
const create=async(variant:"traditional"|"battle",privateGame=false)=>{const data=await call({action:privateGame?"create_private_challenge":"create_game",variant,minutes,...(variant==="battle"?{formationKey:formation}:{})});if(data?.gameId){if(privateGame){setMessage("Private challenge ready to share.");await load()}else router.push({pathname:"/online/[id]",params:{id:String(data.gameId)}} as never)}};
const join=async(id:string)=>{const data=await call({action:"join_game",gameId:id});if(data?.gameId)router.push({pathname:"/online/[id]",params:{id:String(data.gameId)}} as never)};
const cancel=async(id:string)=>{const data=await call({action:"cancel_game",gameId:id});if(data!==null){setMessage("Challenge cancelled.");await load()}};
const share=async(g:Game)=>{const kind=g.variant==="battle"?"Battle Chess":"Chess Universe";const web=publicChallengeUrl(g.id);const native=nativeChallengeUrl(g.id);await Share.share({title:`${kind} challenge`,message:`You've been challenged to ${kind}. Open the challenge: ${web}\n\nChess Universe app: ${native}`,url:web})};
const incoming=mine.filter(g=>g.status==="waiting"&&g.is_private&&g.invited_user_id===session?.user.id&&g.white_id!==session?.user.id);const sent=mine.filter(g=>g.status==="waiting"&&g.is_private&&g.white_id===session?.user.id);const active=mine.filter(g=>g.status==="active");
if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator color="#d7ff4a" style={{marginTop:80}}/></SafeAreaView>;
return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()} tintColor="#d7ff4a"/>} contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Universe</Text></Pressable><Text style={s.eyebrow}>LIVE</Text><Text style={s.title}>Find your table</Text><Text style={s.intro}>Create, join, challenge, and resume games on the same server-authoritative Chess Universe network.</Text>{!session?<View style={s.card}><Text style={s.cardTitle}>Sign in to play online.</Text><Pressable style={s.primary} onPress={()=>router.push("/account" as never)}><Text style={s.primaryText}>Sign in</Text></Pressable></View>:<>{message?<Text style={s.message}>{message}</Text>:null}<Section title="NEW GAME"><Text style={s.small}>TIME CONTROL</Text><View style={s.choiceRow}>{times.map(t=><Pressable key={t} onPress={()=>setMinutes(t)} style={[s.choice,minutes===t&&s.choiceActive]}><Text style={[s.choiceText,minutes===t&&s.choiceTextActive]}>{t===0?"Untimed":`${t} min`}</Text></Pressable>)}</View><View style={s.actions}><Pressable disabled={busy} onPress={()=>void create("traditional")} style={s.primary}><Text style={s.primaryText}>Create Classic</Text></Pressable><Pressable disabled={busy} onPress={()=>void create("traditional",true)} style={s.secondary}><Text style={s.secondaryText}>Private invite</Text></Pressable></View></Section>
<Section title="BATTLE CHESS"><Text style={s.small}>FORMATION</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.formations}>{available.map(f=><Pressable key={f.key} onPress={()=>setFormation(f.key)} style={[s.formation,formation===f.key&&s.formationActive]}><Text style={s.backRank}>{f.backRank.toUpperCase()}</Text><Text style={s.formationName}>{f.name}</Text><Text style={s.formationText}>{f.description}</Text></Pressable>)}</ScrollView><View style={s.actions}><Pressable disabled={busy} onPress={()=>void create("battle")} style={s.primary}><Text style={s.primaryText}>Create Battle</Text></Pressable><Pressable disabled={busy} onPress={()=>void create("battle",true)} style={s.secondary}><Text style={s.secondaryText}>Private Battle</Text></Pressable></View></Section>
{incoming.length>0&&<Section title="CHALLENGES FOR YOU">{incoming.map(g=><View key={g.id} style={s.card}><GameInfo game={g}/><Pressable onPress={()=>void join(g.id)} style={s.primary}><Text style={s.primaryText}>Accept challenge</Text></Pressable></View>)}</Section>}
{active.length>0&&<Section title="YOUR ACTIVE GAMES">{active.map(g=><GameCard key={g.id} game={g} action="Resume" onPress={()=>router.push({pathname:"/online/[id]",params:{id:g.id}} as never)}/>)}</Section>}
{sent.length>0&&<Section title="YOUR PRIVATE INVITES">{sent.map(g=><View key={g.id} style={s.card}><GameInfo game={g}/><View style={s.actions}><Pressable onPress={()=>void share(g)} style={s.primary}><Text style={s.primaryText}>Share invite</Text></Pressable><Pressable onPress={()=>void cancel(g.id)} style={s.secondary}><Text style={s.secondaryText}>Cancel</Text></Pressable></View></View>)}</Section>}
<Section title="OPEN CLASSIC GAMES">{games.filter(g=>g.variant!=="battle").map(g=><GameCard key={g.id} game={g} action="Join" onPress={()=>void join(g.id)}/>)}{games.filter(g=>g.variant!=="battle").length===0&&<Text style={s.empty}>No open Classic games right now.</Text>}</Section><Section title="OPEN BATTLE GAMES">{games.filter(g=>g.variant==="battle").map(g=><GameCard key={g.id} game={g} action="Join Battle" onPress={()=>void join(g.id)}/>)}{games.filter(g=>g.variant==="battle").length===0&&<Text style={s.empty}>No open Battle games right now.</Text>}</Section></>}</ScrollView></SafeAreaView>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function GameInfo({game}:{game:Game}){return <><View style={s.row}><Text style={s.kind}>{game.variant==="battle"?"BATTLE":"CLASSIC"}</Text><Text style={s.time}>{game.time_control_minutes===0?"Untimed":`${game.time_control_minutes} min`}</Text></View><Text style={s.cardTitle}>{game.is_private?"Private challenge":"Open table"}</Text>{game.variant==="battle"&&<Text style={s.meta}>{battleFormations.find(f=>f.key===game.battle_formation_key)?.name??"Classic Line"}</Text>}</>}
function GameCard({game,action,onPress}:{game:Game;action:string;onPress:()=>void}){return <Pressable onPress={onPress} style={s.card}><GameInfo game={game}/><Text style={s.action}>{action} →</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0b0e0f"},content:{padding:22,paddingBottom:44},back:{color:"#9ca7a3",fontSize:15,fontWeight:"700",marginTop:8},eyebrow:{color:"#d7ff4a",fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:32},title:{color:"#f5f7f0",fontSize:37,fontWeight:"900",letterSpacing:-1.4,marginTop:5},intro:{color:"#929d99",fontSize:14,lineHeight:21,marginTop:8},section:{marginTop:24,gap:9},sectionTitle:{color:"#71807a",fontSize:10,fontWeight:"900",letterSpacing:1.6},small:{color:"#71807a",fontSize:9,fontWeight:"900",letterSpacing:1.3},choiceRow:{flexDirection:"row",gap:6},choice:{flex:1,borderWidth:1,borderColor:"#293332",borderRadius:11,paddingVertical:10,alignItems:"center"},choiceActive:{backgroundColor:"#d7ff4a",borderColor:"#d7ff4a"},choiceText:{color:"#9ca7a3",fontSize:10,fontWeight:"800"},choiceTextActive:{color:"#0b0e0f"},actions:{flexDirection:"row",gap:8,marginTop:8},primary:{flex:1,backgroundColor:"#d7ff4a",borderRadius:13,padding:13,alignItems:"center"},primaryText:{color:"#0b0e0f",fontWeight:"900",fontSize:12},secondary:{flex:1,borderWidth:1,borderColor:"#3a4643",borderRadius:13,padding:13,alignItems:"center"},secondaryText:{color:"#f5f7f0",fontWeight:"800",fontSize:12},formations:{gap:8,paddingRight:10},formation:{width:190,backgroundColor:"#151a1b",borderRadius:16,padding:14,borderWidth:1,borderColor:"#273031"},formationActive:{borderColor:"#d7ff4a"},backRank:{color:"#d7ff4a",fontSize:11,fontWeight:"900",letterSpacing:2},formationName:{color:"#f5f7f0",fontSize:15,fontWeight:"900",marginTop:8},formationText:{color:"#82908a",fontSize:11,lineHeight:16,marginTop:4},card:{backgroundColor:"#151a1b",borderRadius:18,padding:17,borderWidth:1,borderColor:"#273031"},row:{flexDirection:"row",justifyContent:"space-between"},kind:{color:"#d7ff4a",fontSize:9,fontWeight:"900",letterSpacing:1.3},time:{color:"#87928e",fontSize:10,fontWeight:"800"},cardTitle:{color:"#f5f7f0",fontSize:18,fontWeight:"900",marginTop:9},meta:{color:"#89948f",fontSize:11,marginTop:4},action:{color:"#d7ff4a",fontSize:12,fontWeight:"800",marginTop:11},empty:{color:"#77837e",fontSize:13},message:{color:"#d8dfda",fontSize:12,marginTop:15}});
