import { router } from "expo-router";
import { useCallback,useEffect,useState } from "react";
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useSession } from "@/lib/session";
import { supabase } from "@/lib/supabase";
type Game={id:string;white_id:string|null;black_id:string|null;status:string;variant:string;time_control_minutes:number;created_at:string;is_private:boolean;invited_user_id:string|null};
export default function Online(){const {session,loading}=useSession();const [games,setGames]=useState<Game[]>([]);const [active,setActive]=useState<Game[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const load=useCallback(async()=>{if(!supabase||!session)return;setBusy(true);const id=session.user.id;await supabase.functions.invoke("online-game",{body:{action:"refresh_lobby"}});const select="id,white_id,black_id,status,variant,time_control_minutes,created_at,is_private,invited_user_id";const [waiting,mine]=await Promise.all([supabase.from("games").select(select).eq("status","waiting").eq("is_private",false).order("created_at",{ascending:false}).limit(40),supabase.from("games").select(select).in("status",["waiting","active"]).or(`white_id.eq.${id},black_id.eq.${id},invited_user_id.eq.${id}`).order("created_at",{ascending:false})]);setGames((waiting.data??[]) as Game[]);setActive(((mine.data??[]) as Game[]).filter(g=>g.status==="active"||(g.is_private&&g.invited_user_id===id)));setMessage(waiting.error?.message??mine.error?.message??"");setBusy(false)},[session?.user.id]);useEffect(()=>{void load();if(!supabase||!session)return;const channel=supabase.channel("mobile-lobby").on("postgres_changes",{event:"*",schema:"public",table:"games"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load,session?.user.id]);if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator color="#d7ff4a" style={{marginTop:80}}/></SafeAreaView>;return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()} tintColor="#d7ff4a"/>} contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Universe</Text></Pressable><Text style={s.eyebrow}>LIVE</Text><Text style={s.title}>Online</Text><Text style={s.intro}>The native lobby is connected to the same server-authoritative Chess Universe games as the web app.</Text>{!session?<View style={s.card}><Text style={s.cardTitle}>Sign in to play online.</Text><Pressable style={s.primary} onPress={()=>router.push("/account" as never)}><Text style={s.primaryText}>Sign in</Text></Pressable></View>:<>{message?<Text style={s.error}>{message}</Text>:null}{active.length>0&&<Section title="YOUR GAMES">{active.map(g=><GameCard key={g.id} game={g} action="Open game"/>)}</Section>}<Section title="OPEN CLASSIC GAMES">{games.filter(g=>g.variant!=="battle").map(g=><GameCard key={g.id} game={g} action="View / join"/>)}{games.filter(g=>g.variant!=="battle").length===0&&<Text style={s.empty}>No open Classic games right now.</Text>}</Section><Section title="BATTLE CHESS">{games.filter(g=>g.variant==="battle").map(g=><GameCard key={g.id} game={g} action="View / join"/>)}{games.filter(g=>g.variant==="battle").length===0&&<Text style={s.empty}>No open Battle games right now.</Text>}</Section></>}</ScrollView></SafeAreaView>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function GameCard({game,action}:{game:Game;action:string}){return <Pressable onPress={()=>router.push({pathname:"/online/[id]",params:{id:game.id}} as never)} style={s.card}><View style={s.row}><Text style={s.kind}>{game.variant==="battle"?"BATTLE":"CLASSIC"}</Text><Text style={s.time}>{game.time_control_minutes===0?"Untimed":`${game.time_control_minutes} min`}</Text></View><Text style={s.cardTitle}>{game.status==="active"?"Game in progress":game.is_private?"Private challenge":"Open table"}</Text><Text style={s.action}>{action} →</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0b0e0f"},content:{padding:22,paddingBottom:44},back:{color:"#9ca7a3",fontSize:15,fontWeight:"700",marginTop:8},eyebrow:{color:"#d7ff4a",fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:32},title:{color:"#f5f7f0",fontSize:39,fontWeight:"900",letterSpacing:-1.4,marginTop:5},intro:{color:"#929d99",fontSize:14,lineHeight:21,marginTop:8},section:{marginTop:24,gap:9},sectionTitle:{color:"#71807a",fontSize:10,fontWeight:"900",letterSpacing:1.6},card:{backgroundColor:"#151a1b",borderRadius:18,padding:17,borderWidth:1,borderColor:"#273031"},row:{flexDirection:"row",justifyContent:"space-between"},kind:{color:"#d7ff4a",fontSize:9,fontWeight:"900",letterSpacing:1.3},time:{color:"#87928e",fontSize:10,fontWeight:"800"},cardTitle:{color:"#f5f7f0",fontSize:18,fontWeight:"900",marginTop:9},action:{color:"#d7ff4a",fontSize:12,fontWeight:"800",marginTop:11},empty:{color:"#77837e",fontSize:13},primary:{backgroundColor:"#d7ff4a",borderRadius:13,padding:13,alignItems:"center",marginTop:15},primaryText:{color:"#0b0e0f",fontWeight:"900"},error:{color:"#ef9b8f",marginTop:15}});
