import { useLocalSearchParams,router } from "expo-router";
import { useEffect,useMemo,useState } from "react";
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View,useWindowDimensions } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Chess,type Color,type PieceSymbol,type Square } from "chess.js";
import { supabase } from "@/lib/supabase";
const glyphs:Record<Color,Record<PieceSymbol,string>>={w:{k:"♔",q:"♕",r:"♖",b:"♗",n:"♘",p:"♙"},b:{k:"♚",q:"♛",r:"♜",b:"♝",n:"♞",p:"♟"}};const files=["a","b","c","d","e","f","g","h"] as const;type Move={ply:number;san:string;fen_after:string;from_square:string;to_square:string};
export default function Replay(){const {id}=useLocalSearchParams<{id:string}>();const {width}=useWindowDimensions();const size=Math.min(width-44,500);const [moves,setMoves]=useState<Move[]>([]);const [step,setStep]=useState(0);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");useEffect(()=>{if(!supabase||!id){setLoading(false);return}void supabase.from("game_moves").select("ply,san,fen_after,from_square,to_square").eq("game_id",id).order("ply",{ascending:true}).then(({data,error})=>{setMoves((data??[]) as Move[]);setMessage(error?.message??"");setLoading(false)})},[id]);const game=useMemo(()=>{try{return step===0?new Chess():new Chess(moves[step-1]?.fen_after)}catch{return new Chess()}},[moves,step]);const last=step>0?moves[step-1]:null;if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator color="#d7ff4a" style={{marginTop:80}}/></SafeAreaView>;return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← My Games</Text></Pressable><Text style={s.eyebrow}>REPLAY</Text><Text style={s.title}>Game review</Text>{message?<Text style={s.error}>{message}</Text>:<><View style={[s.board,{width:size,height:size}]}>{Array.from({length:8},(_,r)=>8-r).flatMap((rank,row)=>files.map((file,col)=>{const sq=`${file}${rank}` as Square;const p=game.get(sq);const dark=(row+col)%2===1;const recent=last&&(last.from_square===sq||last.to_square===sq);return <View key={sq} style={[s.square,{width:size/8,height:size/8},dark?s.dark:s.light,recent&&s.last]}>{p&&<Text style={[s.piece,{fontSize:size/11.5}]}>{glyphs[p.color][p.type]}</Text>}</View>}))}</View><View style={s.controls}><Pressable disabled={step===0} onPress={()=>setStep(0)}><Text style={[s.control,step===0&&s.disabled]}>|←</Text></Pressable><Pressable disabled={step===0} onPress={()=>setStep(v=>Math.max(0,v-1))}><Text style={[s.control,step===0&&s.disabled]}>←</Text></Pressable><Text style={s.counter}>{step}/{moves.length}</Text><Pressable disabled={step===moves.length} onPress={()=>setStep(v=>Math.min(moves.length,v+1))}><Text style={[s.control,step===moves.length&&s.disabled]}>→</Text></Pressable><Pressable disabled={step===moves.length} onPress={()=>setStep(moves.length)}><Text style={[s.control,step===moves.length&&s.disabled]}>→|</Text></Pressable></View><View style={s.moves}>{moves.map((m,i)=><Pressable key={`${m.ply}-${i}`} onPress={()=>setStep(i+1)}><Text style={[s.move,step===i+1&&s.moveActive]}>{i%2===0?`${Math.floor(i/2)+1}. `:""}{m.san}</Text></Pressable>)}</View></>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0b0e0f"},content:{padding:22,paddingBottom:44},back:{color:"#9ca7a3",fontSize:15,fontWeight:"700",marginTop:8},eyebrow:{color:"#d7ff4a",fontSize:11,fontWeight:"900",letterSpacing:2,marginTop:26},title:{color:"#f5f7f0",fontSize:32,fontWeight:"900",marginTop:5,marginBottom:18},board:{flexDirection:"row",flexWrap:"wrap",alignSelf:"center",borderRadius:12,overflow:"hidden"},square:{alignItems:"center",justifyContent:"center"},light:{backgroundColor:"#d9ded5"},dark:{backgroundColor:"#65736b"},last:{borderWidth:3,borderColor:"#d7ff4a"},piece:{color:"#0b0e0f"},controls:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",backgroundColor:"#151a1b",borderRadius:15,padding:14,marginTop:14},control:{color:"#d7ff4a",fontSize:19,fontWeight:"900"},disabled:{opacity:.25},counter:{color:"#f5f7f0",fontSize:12,fontWeight:"800"},moves:{flexDirection:"row",flexWrap:"wrap",gap:9,marginTop:15},move:{color:"#a5afab",fontSize:13,fontWeight:"700",padding:5},moveActive:{color:"#0b0e0f",backgroundColor:"#d7ff4a",borderRadius:6},error:{color:"#ef9b8f"}});
