import { router,useLocalSearchParams } from "expo-router";
import { useEffect,useState } from "react";
import { ActivityIndicator,Pressable,StyleSheet,Text,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useSession } from "@/lib/session";
import { supabase } from "@/lib/supabase";
type Info={gameId:string;timeControlMinutes:number;isRematch:boolean;variant:string;formationKey:string|null;challenger:{id:string;username:string;rating:number}|null};
export default function ChallengeEntry(){const {id}=useLocalSearchParams<{id:string}>();const {session,loading:sessionLoading}=useSession();const [info,setInfo]=useState<Info|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");useEffect(()=>{if(!supabase||!session||!id){setLoading(false);return}setLoading(true);void supabase.functions.invoke("online-game",{body:{action:"inspect_challenge",gameId:id}}).then(({data,error})=>{setInfo((data?.challenge??null) as Info|null);setMessage(error?.message??(!data?.challenge?"This challenge is no longer available.":""));setLoading(false)})},[id,session?.user.id]);const accept=async()=>{if(!supabase||!id)return;setLoading(true);const {data,error}=await supabase.functions.invoke("online-game",{body:{action:"join_game",gameId:id}});if(error){setMessage(error.message);setLoading(false);return}router.replace({pathname:"/online/[id]",params:{id:String(data?.gameId??id)}} as never)};if(sessionLoading||loading)return <SafeAreaView style={s.safe}><ActivityIndicator color="#d7ff4a" style={{marginTop:90}}/></SafeAreaView>;return <SafeAreaView style={s.safe}><View style={s.content}><Text style={s.eyebrow}>PRIVATE CHALLENGE</Text><Text style={s.title}>{info?.challenger?`${info.challenger.username} challenged you.`:"You’ve been challenged."}</Text>{info&&<Text style={s.text}>{info.variant==="battle"?`Battle Chess · ${info.formationKey??"classic"}`:"Classic Chess"} · {info.timeControlMinutes===0?"Untimed":`${info.timeControlMinutes} min`}{info.isRematch?" · Rematch":""}</Text>}{message?<Text style={s.error}>{message}</Text>:null}{!session?<><Text style={s.text}>Sign in first. The invite will still be here afterward.</Text><Pressable onPress={()=>router.replace("/account" as never)} style={s.button}><Text style={s.buttonText}>Sign in</Text></Pressable></>:info?<Pressable onPress={()=>void accept()} style={s.button}><Text style={s.buttonText}>Accept challenge</Text></Pressable>:<Pressable onPress={()=>router.replace("/online" as never)} style={s.secondary}><Text style={s.secondaryText}>Open online lobby</Text></Pressable>}</View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0b0e0f"},content:{flex:1,justifyContent:"center",padding:26},eyebrow:{color:"#d7ff4a",fontWeight:"900",letterSpacing:2},title:{color:"#f5f7f0",fontSize:36,fontWeight:"900",marginTop:10},text:{color:"#929d99",fontSize:16,lineHeight:23,marginTop:12},error:{color:"#ef9b8f",fontSize:13,lineHeight:20,marginTop:14},button:{backgroundColor:"#d7ff4a",padding:16,borderRadius:18,alignItems:"center",marginTop:28},buttonText:{color:"#0b0e0f",fontWeight:"900",fontSize:16},secondary:{borderWidth:1,borderColor:"#3a4643",padding:16,borderRadius:18,alignItems:"center",marginTop:28},secondaryText:{color:"#f5f7f0",fontWeight:"900"}});
