import * as Haptics from "expo-haptics";
import { router,useLocalSearchParams } from "expo-router";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,useWindowDimensions,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Chess,type Color,type PieceSymbol,type Square } from "chess.js";
import { useSession } from "@/lib/session";
import { supabase } from "@/lib/supabase";
const glyphs:Record<Color,Record<PieceSymbol,string>>={w:{k:"♔",q:"♕",r:"♖",b:"♗",n:"♘",p:"♙"},b:{k:"♚",q:"♛",r:"♜",b:"♝",n:"♞",p:"♟"}};
const whiteFiles=["a","b","c","d","e","f","g","h"] as const;const blackFiles=["h","g","f","e","d","c","b","a"] as const;
type Game={id:string;white_id:string|null;black_id:string|null;status:"waiting"|"active"|"completed"|"cancelled";result:"white"|"black"|"draw"|null;result_reason:string|null;variant:string;fen:string;current_turn:"w"|"b";time_control_minutes:number;increment_seconds:number;white_time_ms:number|null;black_time_ms:number|null;last_move_at:string|null;draw_offer_by:string|null;rematch_game_id:string|null;white_rating_before:number|null;white_rating_after:number|null;black_rating_before:number|null;black_rating_after:number|null};
type Move={id:number;ply:number;from_square:Square;to_square:Square;san:string};type Profile={id:string;username:string;rating:number};
function remaining(g:Game,c:"w"|"b",now:number){if(!g.time_control_minutes)return 0;const stored=c==="w"?(g.white_time_ms??g.time_control_minutes*60000):(g.black_time_ms??g.time_control_minutes*60000);if(g.status!=="active"||g.current_turn!==c||!g.last_move_at)return Math.max(0,stored);return Math.max(0,stored-Math.max(0,now-Date.parse(g.last_move_at)))}
function clock(ms:number){const n=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`}
export default function OnlineMatch(){const {id}=useLocalSearchParams<{id:string}>();const {session,loading:sessionLoading}=useSession();const {width}=useWindowDimensions();const size=Math.min(width-28,520);const [game,setGame]=useState<Game|null>(null);const [moves,setMoves]=useState<Move[]>([]);const [profiles,setProfiles]=useState<Record<string,Profile>>({});const [selected,setSelected]=useState<Square|null>(null);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("Loading game…");const [now,setNow]=useState(Date.now());const [opponentOnline,setOpponentOnline]=useState(false);const timeoutClaimed=useRef(false);
const load=useCallback(async()=>{if(!supabase||!id)return;const [{data,error},{data:moveData}]=await Promise.all([supabase.from("games").select("id,white_id,black_id,status,result,result_reason,variant,fen,current_turn,time_control_minutes,increment_seconds,white_time_ms,black_time_ms,last_move_at,draw_offer_by,rematch_game_id,white_rating_before,white_rating_after,black_rating_before,black_rating_after").eq("id",id).single(),supabase.from("game_moves").select("id,ply,from_square,to_square,san").eq("game_id",id).order("ply",{ascending:true})]);if(error){setMessage(error.message);return}const row=data as Game;setGame(row);setMoves((moveData??[]) as Move[]);const ids=[row.white_id,row.black_id].filter(Boolean) as string[];if(ids.length){const {data:p}=await supabase.from("profiles").select("id,username,rating").in("id",ids);setProfiles(Object.fromEntries(((p??[]) as Profile[]).map(x=>[x.id,x])))}setMessage("")},[id]);useEffect(()=>{void load()},[load]);
const myColor=game&&session?(game.white_id===session.user.id?"w":game.black_id===session.user.id?"b":null):null;const opponentId=game&&myColor?(myColor==="w"?game.black_id:game.white_id):null;
useEffect(()=>{if(!supabase||!id||!myColor)return;const ch=supabase.channel(`mobile-game:${id}`,{config:{presence:{key:myColor}}}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"games",filter:`id=eq.${id}`},p=>{setGame(p.new as Game);setSelected(null);timeoutClaimed.current=false}).on("postgres_changes",{event:"INSERT",schema:"public",table:"game_moves",filter:`game_id=eq.${id}`},p=>setMoves(cur=>cur.some(m=>m.id===(p.new as Move).id)?cur:[...cur,p.new as Move].sort((a,b)=>a.ply-b.ply))).on("presence",{event:"sync"},()=>{const state=ch.presenceState() as Record<string,unknown[]>;setOpponentOnline(Boolean(state[myColor==="w"?"b":"w"]?.length))}).subscribe(status=>{if(status==="SUBSCRIBED")void ch.track({side:myColor,online_at:new Date().toISOString()});if(status==="CHANNEL_ERROR"||status==="TIMED_OUT"||status==="CLOSED")setOpponentOnline(false)});return()=>{void supabase.removeChannel(ch)}},[id,myColor]);
useEffect(()=>{if(game?.status!=="active"||!game.time_control_minutes)return;const t=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(t)},[game?.status,game?.time_control_minutes]);const white=game?remaining(game,"w",now):0;const black=game?remaining(game,"b",now):0;
useEffect(()=>{if(!supabase||!game||game.status!=="active"||!game.time_control_minutes||!myColor||timeoutClaimed.current)return;const active=game.current_turn==="w"?white:black;if(active>0)return;timeoutClaimed.current=true;void supabase.functions.invoke("online-game",{body:{action:"timeout",gameId:id}}).then(()=>load())},[black,game,id,load,myColor,white]);
const chess=useMemo(()=>{try{return new Chess(game?.fen)}catch{return new Chess()}},[game?.fen]);const targets=useMemo(()=>selected?new Set(chess.moves({square:selected,verbose:true}).map(m=>m.to)):new Set<Square>(),[chess,selected]);const isMyTurn=game?.status==="active"&&myColor===game.current_turn;const last=moves.at(-1);const invoke=async(body:Record<string,unknown>)=>{if(!supabase)return;setSaving(true);setMessage("");const {error}=await supabase.functions.invoke("online-game",{body});if(error)setMessage(error.message);await load();setSaving(false)};
const attempt=async(from:Square,to:Square)=>{if(!game||!isMyTurn||saving)return;try{const preview=new Chess(chess.fen());const m=preview.move({from,to,promotion:"q"});if(!m){setMessage("That move isn't legal.");return}setSelected(null);await invoke({action:"move",gameId:id,from:m.from,to:m.to,promotion:m.promotion??null});void Haptics.selectionAsync()}catch{setMessage("That move isn't legal.")}};const tap=(sq:Square)=>{if(!isMyTurn||saving||!myColor)return;const p=chess.get(sq);if(!selected){if(p?.color===myColor)setSelected(sq);return}if(p?.color===myColor){setSelected(sq);return}void attempt(selected,sq)};
const confirmResign=()=>Alert.alert("Resign game?","This ends the game as a loss.",[{text:"Cancel",style:"cancel"},{text:"Resign",style:"destructive",onPress:()=>void invoke({action:"resign",gameId:id})}]);
if(sessionLoading||(!game&&message==="Loading game…"))return <SafeAreaView style={s.safe}><ActivityIndicator color="#d7ff4a" style={{marginTop:80}}/></SafeAreaView>;if(!session)return <SafeAreaView style={s.safe}><View style={s.content}><Text style={s.title}>Sign in required</Text><Pressable style={s.primary} onPress={()=>router.replace("/account" as never)}><Text style={s.primaryText}>Sign in</Text></Pressable></View></SafeAreaView>;
const files=myColor==="b"?blackFiles:whiteFiles;const ranks=myColor==="b"?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1];const opp=opponentId?profiles[opponentId]:undefined;const me=myColor?(myColor==="w"?game?.white_id:game?.black_id):null;const mine=me?profiles[me]:undefined;const result=game?.result==="draw"?"Draw":game?.result===myColor?"You won":game?.result?"You lost":"Game over";
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Online lobby</Text></Pressable><View style={s.header}><View><Text style={s.eyebrow}>{game?.variant==="battle"?"BATTLE CHESS":"ONLINE TABLE"}</Text><Text style={s.title}>{myColor?`You are ${myColor==="w"?"White":"Black"}`:"Spectating"}</Text></View><View style={[s.dot,opponentOnline&&s.dotOnline]}/></View><Text style={s.opponent}>{opp?.username??"Opponent"} {opp?`· ${opp.rating}`:""} · {opponentOnline?"online":"away / reconnecting"}</Text>{game?.time_control_minutes?<View style={s.clocks}><View style={[s.clock,game.current_turn==="b"&&game.status==="active"&&s.clockActive]}><Text style={s.clockName}>BLACK</Text><Text style={s.clockTime}>{clock(black)}</Text></View><View style={[s.clock,game.current_turn==="w"&&game.status==="active"&&s.clockActive]}><Text style={s.clockName}>WHITE</Text><Text style={s.clockTime}>{clock(white)}</Text></View></View>:<Text style={s.untimed}>UNTIMED · safe to leave and resume</Text>}
<View style={[s.board,{width:size,height:size}]}>{ranks.flatMap((rank,row)=>files.map((file,col)=>{const sq=`${file}${rank}` as Square;const p=chess.get(sq);const dark=(row+col)%2===1;const recent=last&&(last.from_square===sq||last.to_square===sq);const check=chess.inCheck()&&p?.type==="k"&&p.color===chess.turn();return <Pressable key={sq} onPress={()=>tap(sq)} style={[s.square,{width:size/8,height:size/8},dark?s.dark:s.light,recent&&s.last,check&&s.check,selected===sq&&s.selected]}>{targets.has(sq)&&<View style={s.target}/>} {p&&<Text style={[s.piece,{fontSize:size/11.5}]}>{glyphs[p.color][p.type]}</Text>}</Pressable>}))}</View>
<Text style={s.status}>{game?.status==="completed"?`${result}${game.result_reason?` · ${game.result_reason.replaceAll("_"," ")}`:""}`:game?.status==="waiting"?"Waiting for an opponent…":isMyTurn?(chess.inCheck()?"You're in check — your move":"Your move"):"Opponent's move"}</Text>{message?<Text style={s.message}>{message}</Text>:null}{game?.status==="active"&&myColor?<View style={s.actions}><Pressable disabled={saving||!!game.draw_offer_by} onPress={()=>void invoke({action:"offer_draw",gameId:id})} style={s.secondary}><Text style={s.secondaryText}>{game.draw_offer_by===session.user.id?"Draw offered":"Offer draw"}</Text></Pressable><Pressable disabled={saving} onPress={confirmResign} style={s.danger}><Text style={s.dangerText}>Resign</Text></Pressable></View>:null}{game?.draw_offer_by&&game.draw_offer_by!==session.user.id&&game.status==="active"?<View style={s.offer}><Text style={s.offerTitle}>Opponent offered a draw.</Text><View style={s.actions}><Pressable onPress={()=>void invoke({action:"accept_draw",gameId:id})} style={s.primary}><Text style={s.primaryText}>Accept</Text></Pressable><Pressable onPress={()=>void invoke({action:"decline_draw",gameId:id})} style={s.secondary}><Text style={s.secondaryText}>Decline</Text></Pressable></View></View>:null}{game?.status==="completed"&&myColor?<View style={s.offer}><Text style={s.offerTitle}>{result}</Text><Text style={s.rating}>{mine?.rating?`Current rating ${mine.rating}`:""}</Text><Pressable style={s.primary} onPress={()=>void invoke({action:game.rematch_game_id?"accept_rematch":"create_rematch",gameId:id})}><Text style={s.primaryText}>{game.rematch_game_id?"Accept rematch":"Request rematch"}</Text></Pressable></View>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#0b0e0f"},content:{padding:14,paddingBottom:44},back:{color:"#9ca7a3",fontSize:14,fontWeight:"700",margin:8},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginHorizontal:8,marginTop:16},eyebrow:{color:"#d7ff4a",fontSize:10,fontWeight:"900",letterSpacing:1.7},title:{color:"#f5f7f0",fontSize:27,fontWeight:"900",marginTop:3},dot:{width:10,height:10,borderRadius:5,backgroundColor:"#59635f"},dotOnline:{backgroundColor:"#d7ff4a"},opponent:{color:"#8e9995",fontSize:12,marginHorizontal:8,marginTop:6,marginBottom:12},clocks:{flexDirection:"row",gap:8,marginHorizontal:8,marginBottom:10},clock:{flex:1,backgroundColor:"#151a1b",borderRadius:12,padding:9,borderWidth:1,borderColor:"#273031"},clockActive:{borderColor:"#d7ff4a"},clockName:{color:"#71807a",fontSize:8,fontWeight:"900",letterSpacing:1.2},clockTime:{color:"#f5f7f0",fontSize:21,fontWeight:"900"},untimed:{color:"#d7ff4a",fontSize:10,fontWeight:"800",marginHorizontal:8,marginBottom:10},board:{flexDirection:"row",flexWrap:"wrap",alignSelf:"center",borderRadius:12,overflow:"hidden"},square:{alignItems:"center",justifyContent:"center"},light:{backgroundColor:"#d9ded5"},dark:{backgroundColor:"#65736b"},selected:{backgroundColor:"#d7ff4a"},last:{borderWidth:3,borderColor:"#d7ff4a99"},check:{backgroundColor:"#d46a5c"},target:{position:"absolute",width:13,height:13,borderRadius:7,backgroundColor:"#0b0e0f66"},piece:{color:"#0b0e0f"},status:{color:"#f5f7f0",fontSize:14,fontWeight:"900",margin:10},message:{color:"#efb18f",fontSize:12,marginHorizontal:10},actions:{flexDirection:"row",gap:9,marginTop:10},primary:{flex:1,backgroundColor:"#d7ff4a",borderRadius:13,padding:13,alignItems:"center"},primaryText:{color:"#0b0e0f",fontWeight:"900"},secondary:{flex:1,borderWidth:1,borderColor:"#3a4643",borderRadius:13,padding:13,alignItems:"center"},secondaryText:{color:"#f5f7f0",fontWeight:"800"},danger:{flex:1,borderWidth:1,borderColor:"#6b3936",backgroundColor:"#251817",borderRadius:13,padding:13,alignItems:"center"},dangerText:{color:"#f19a91",fontWeight:"900"},offer:{backgroundColor:"#151a1b",borderRadius:18,padding:16,margin:10,marginTop:16,borderWidth:1,borderColor:"#273031"},offerTitle:{color:"#f5f7f0",fontSize:16,fontWeight:"900"},rating:{color:"#8c9793",fontSize:12,marginTop:5}});
