import type { Session } from "@supabase/supabase-js";
import { readJson,writeJson } from "@/lib/storage";
import { supabase } from "@/lib/supabase";
type Preferences={mobileAcademyComplete?:string[];[key:string]:unknown};
const ACADEMY_KEY="academy-complete-v1";const PUZZLE_KEY="puzzle-progress-v1";
function strings(value:unknown){return Array.isArray(value)?value.filter((v):v is string=>typeof v==="string"):[]}
function union(a:string[],b:string[]){return [...new Set([...a,...b])]}
export async function loadAcademyProgress(session:Session|null){const local=await readJson<string[]>(ACADEMY_KEY,[]);if(!session||!supabase)return local;const {data}=await supabase.from("player_progress").select("preferences").eq("user_id",session.user.id).maybeSingle();const prefs=(data?.preferences&&typeof data.preferences==="object"?data.preferences:{}) as Preferences;const merged=union(local,strings(prefs.mobileAcademyComplete));await writeJson(ACADEMY_KEY,merged);await supabase.from("player_progress").upsert({user_id:session.user.id,preferences:{...prefs,mobileAcademyComplete:merged},updated_at:new Date().toISOString()},{onConflict:"user_id"});return merged}
export async function saveAcademyProgress(session:Session|null,complete:string[]){const merged=[...new Set(complete)];await writeJson(ACADEMY_KEY,merged);if(!session||!supabase)return;const {data}=await supabase.from("player_progress").select("preferences").eq("user_id",session.user.id).maybeSingle();const prefs=(data?.preferences&&typeof data.preferences==="object"?data.preferences:{}) as Preferences;await supabase.from("player_progress").upsert({user_id:session.user.id,preferences:{...prefs,mobileAcademyComplete:merged},updated_at:new Date().toISOString()},{onConflict:"user_id"})}
export async function loadPuzzleProgress(session:Session|null){const local=await readJson<string[]>(PUZZLE_KEY,[]);if(!session||!supabase)return local;const {data}=await supabase.from("player_progress").select("puzzle_progress").eq("user_id",session.user.id).maybeSingle();const merged=union(local,strings(data?.puzzle_progress));await writeJson(PUZZLE_KEY,merged);await supabase.from("player_progress").upsert({user_id:session.user.id,puzzle_progress:merged,updated_at:new Date().toISOString()},{onConflict:"user_id"});return merged}
export async function recordPuzzleSolved(session:Session|null,id:string,existing:string[]){const next=union(existing,[id]);await writeJson(PUZZLE_KEY,next);if(session&&supabase)await supabase.from("player_progress").upsert({user_id:session.user.id,puzzle_progress:next,updated_at:new Date().toISOString()},{onConflict:"user_id"});return next}
