import * as Haptics from "expo-haptics";
import { useEffect, useMemo, useRef, useState } from "react";
import { Modal, Pressable, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { Chess, type Color, type PieceSymbol, type Square } from "chess.js";
import { aiLevels, chooseAiMove, type AiLevel } from "@/lib/ai";
import { clockPresets, formatClock } from "@/lib/clock";

const glyphs: Record<Color, Record<PieceSymbol,string>>={w:{k:"♔",q:"♕",r:"♖",b:"♗",n:"♘",p:"♙"},b:{k:"♚",q:"♛",r:"♜",b:"♝",n:"♞",p:"♟"}};
const whiteFiles=["a","b","c","d","e","f","g","h"] as const;
const blackFiles=["h","g","f","e","d","c","b","a"] as const;
type Promotion={from:Square;to:Square}|null;

export function PracticeGame(){
 const {width}=useWindowDimensions();const size=Math.min(width-28,520);
 const [game,setGame]=useState(()=>new Chess());const [selected,setSelected]=useState<Square|null>(null);const [level,setLevel]=useState<AiLevel>("beginner");const [thinking,setThinking]=useState(false);const [flipped,setFlipped]=useState(false);const [promotion,setPromotion]=useState<Promotion>(null);
 const [clockIndex,setClockIndex]=useState(0);const preset=clockPresets[clockIndex];const [whiteTime,setWhiteTime]=useState(preset.seconds);const [blackTime,setBlackTime]=useState(preset.seconds);const aiTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const targets=useMemo(()=>selected?new Set(game.moves({square:selected,verbose:true}).map(m=>m.to)):new Set<Square>(),[game,selected]);const current=aiLevels.find(x=>x.id===level)!;
 const reset=()=>{if(aiTimer.current)clearTimeout(aiTimer.current);setThinking(false);setSelected(null);setPromotion(null);setGame(new Chess());setWhiteTime(preset.seconds);setBlackTime(preset.seconds);};
 useEffect(()=>()=>{if(aiTimer.current)clearTimeout(aiTimer.current)},[]);
 useEffect(()=>{if(!preset.seconds||game.isGameOver())return;const id=setInterval(()=>{if(game.turn()==="w"&&!thinking)setWhiteTime(t=>Math.max(0,t-1));else setBlackTime(t=>Math.max(0,t-1));},1000);return()=>clearInterval(id)},[game,thinking,preset.seconds]);
 useEffect(()=>{if((whiteTime===0||blackTime===0)&&preset.seconds){if(aiTimer.current)clearTimeout(aiTimer.current);setThinking(false)}},[whiteTime,blackTime,preset.seconds]);
 const clone=(g:Chess)=>{const n=new Chess();if(g.pgn())n.loadPgn(g.pgn());return n};
 const playAi=(position:Chess)=>{if(position.isGameOver()||blackTime===0)return;setThinking(true);aiTimer.current=setTimeout(()=>{const next=clone(position);const move=chooseAiMove(next,level);if(move){next.move(move);if(preset.increment)setBlackTime(t=>t+preset.increment)}setGame(next);setThinking(false);void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)},current.delay)};
 const finishPlayerMove=(from:Square,to:Square,piece:"q"|"r"|"b"|"n"="q")=>{const next=clone(game);try{next.move({from,to,promotion:piece});if(preset.increment)setWhiteTime(t=>t+preset.increment);setGame(next);setSelected(null);setPromotion(null);void Haptics.selectionAsync();playAi(next)}catch{setSelected(null);setPromotion(null)}};
 const tap=(sq:Square)=>{if(thinking||game.turn()!=="w"||game.isGameOver()||whiteTime===0)return;const piece=game.get(sq);if(!selected){if(piece?.color==="w")setSelected(sq);return}if(piece?.color==="w"){setSelected(sq);return}if(!targets.has(sq)){setSelected(null);return}const moving=game.get(selected);if(moving?.type==="p"&&sq.endsWith("8")){setPromotion({from:selected,to:sq});return}finishPlayerMove(selected,sq)};
 const undoRound=()=>{if(thinking||game.history().length<2)return;const sans=game.history().slice(0,-2);const next=new Chess();sans.forEach(s=>next.move(s));setGame(next);setSelected(null)};
 const files=flipped?blackFiles:whiteFiles;const ranks=flipped?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1];const history=game.history({verbose:true});const last=history.at(-1);
 const timeout=preset.seconds&&(whiteTime===0||blackTime===0);const status=timeout?(whiteTime===0?"Time — Black wins":"Time — White wins"):game.isCheckmate()?"Checkmate":game.isDraw()?"Draw":thinking?`${current.label} is thinking…`:game.inCheck()?"Check — your move":"Your move";
 return <View>
  <Text style={styles.label}>AI LEVEL</Text><View style={styles.levels}>{aiLevels.map(item=><Pressable key={item.id} onPress={()=>{setLevel(item.id);reset()}} style={[styles.level,item.id===level&&styles.levelActive]}><Text style={[styles.levelText,item.id===level&&styles.levelTextActive]}>{item.label}</Text></Pressable>)}</View><Text style={styles.description}>{current.description}</Text>
  <View style={styles.optionRow}><View style={styles.clockChoices}>{clockPresets.map((c,i)=><Pressable key={c.label} onPress={()=>{setClockIndex(i);setWhiteTime(c.seconds);setBlackTime(c.seconds);setGame(new Chess());setSelected(null)}} style={[styles.clockChoice,i===clockIndex&&styles.clockActive]}><Text style={[styles.clockChoiceText,i===clockIndex&&styles.clockActiveText]}>{c.label}</Text></Pressable>)}</View><Pressable onPress={()=>setFlipped(v=>!v)} style={styles.flip}><Text style={styles.flipText}>↻ Flip</Text></Pressable></View>
  {!!preset.seconds&&<View style={styles.clocks}><View style={[styles.clock,game.turn()==="b"&&styles.clockTurn]}><Text style={styles.clockName}>BLACK</Text><Text style={styles.clockTime}>{formatClock(blackTime)}</Text></View><View style={[styles.clock,game.turn()==="w"&&!thinking&&styles.clockTurn]}><Text style={styles.clockName}>WHITE</Text><Text style={styles.clockTime}>{formatClock(whiteTime)}</Text></View></View>}
  <View style={[styles.board,{width:size,height:size}]}>{ranks.flatMap((rank,row)=>files.map((file,col)=>{const sq=`${file}${rank}` as Square;const piece=game.get(sq);const dark=(row+col)%2===1;const target=targets.has(sq);const lastSquare=last&&(last.from===sq||last.to===sq);const checked=game.inCheck()&&piece?.type==="k"&&piece.color===game.turn();return <Pressable key={sq} onPress={()=>tap(sq)} style={[styles.square,{width:size/8,height:size/8},dark?styles.dark:styles.light,lastSquare&&styles.last,checked&&styles.check,selected===sq&&styles.active]}>{target&&<View style={styles.target}/>} {piece&&<Text style={[styles.piece,{fontSize:size/11.5}]}>{glyphs[piece.color][piece.type]}</Text>}</Pressable>}))}</View>
  <View style={styles.footer}><Text style={styles.status}>{status}</Text><View style={styles.actions}><Pressable onPress={undoRound}><Text style={styles.action}>Undo round</Text></Pressable><Pressable onPress={reset}><Text style={styles.action}>New</Text></Pressable></View></View>
  <Modal visible={!!promotion} transparent animationType="fade"><View style={styles.modalBackdrop}><View style={styles.promoCard}><Text style={styles.promoTitle}>Promote pawn</Text><View style={styles.promoRow}>{(["q","r","b","n"] as const).map(p=><Pressable key={p} style={styles.promoPiece} onPress={()=>promotion&&finishPlayerMove(promotion.from,promotion.to,p)}><Text style={styles.promoGlyph}>{glyphs.w[p]}</Text></Pressable>)}</View><Pressable onPress={()=>setPromotion(null)}><Text style={styles.cancel}>Cancel</Text></Pressable></View></View></Modal>
 </View>
}
const styles=StyleSheet.create({label:{color:"#71807a",fontSize:10,fontWeight:"900",letterSpacing:1.5},levels:{flexDirection:"row",gap:7,marginTop:8,marginBottom:7},level:{flex:1,paddingVertical:10,borderRadius:12,borderWidth:1,borderColor:"#293332",alignItems:"center"},levelActive:{backgroundColor:"#d7ff4a",borderColor:"#d7ff4a"},levelText:{color:"#9ca7a3",fontSize:11,fontWeight:"800"},levelTextActive:{color:"#0b0e0f"},description:{color:"#74807c",fontSize:12,marginBottom:12},optionRow:{flexDirection:"row",alignItems:"center",gap:8,marginBottom:10},clockChoices:{flex:1,flexDirection:"row",gap:5},clockChoice:{flex:1,paddingVertical:7,borderRadius:9,borderWidth:1,borderColor:"#293332",alignItems:"center"},clockActive:{backgroundColor:"#202927"},clockChoiceText:{color:"#7f8b87",fontSize:9,fontWeight:"800"},clockActiveText:{color:"#d7ff4a"},flip:{paddingHorizontal:10,paddingVertical:8},flipText:{color:"#d7ff4a",fontSize:11,fontWeight:"900"},clocks:{flexDirection:"row",gap:8,marginBottom:10},clock:{flex:1,backgroundColor:"#151a1b",borderRadius:12,padding:9,borderWidth:1,borderColor:"#273031"},clockTurn:{borderColor:"#d7ff4a"},clockName:{color:"#71807a",fontSize:8,fontWeight:"900",letterSpacing:1.2},clockTime:{color:"#f5f7f0",fontSize:21,fontWeight:"900",marginTop:2},board:{flexDirection:"row",flexWrap:"wrap",borderRadius:12,overflow:"hidden",alignSelf:"center"},square:{alignItems:"center",justifyContent:"center"},light:{backgroundColor:"#d9ded5"},dark:{backgroundColor:"#65736b"},active:{backgroundColor:"#d7ff4a"},last:{borderWidth:3,borderColor:"#d7ff4a99"},check:{backgroundColor:"#d46a5c"},target:{position:"absolute",width:13,height:13,borderRadius:8,backgroundColor:"#0b0e0f66"},piece:{color:"#0b0e0f"},footer:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:14},status:{color:"#f5f7f0",fontSize:13,fontWeight:"800",flex:1},actions:{flexDirection:"row",gap:12},action:{color:"#d7ff4a",fontSize:12,fontWeight:"800"},modalBackdrop:{flex:1,backgroundColor:"#000000aa",alignItems:"center",justifyContent:"center",padding:24},promoCard:{width:"100%",maxWidth:360,backgroundColor:"#151a1b",borderRadius:24,padding:22,borderWidth:1,borderColor:"#303a38"},promoTitle:{color:"#f5f7f0",fontSize:22,fontWeight:"900",textAlign:"center"},promoRow:{flexDirection:"row",justifyContent:"space-between",marginTop:20},promoPiece:{width:62,height:62,borderRadius:16,backgroundColor:"#d9ded5",alignItems:"center",justifyContent:"center"},promoGlyph:{fontSize:42,color:"#0b0e0f"},cancel:{color:"#9ca7a3",fontSize:14,fontWeight:"800",textAlign:"center",marginTop:20}});
