create extension if not exists pgcrypto;

create type public.game_status as enum ('waiting', 'active', 'completed', 'cancelled');
create type public.game_result as enum ('white', 'black', 'draw');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) between 3 and 24),
  rating integer not null default 1200 check (rating >= 0),
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  draws integer not null default 0 check (draws >= 0),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.games (
  id uuid primary key default gen_random_uuid(),
  white_id uuid not null references public.profiles(id) on delete cascade,
  black_id uuid references public.profiles(id) on delete set null,
  status public.game_status not null default 'waiting',
  result public.game_result,
  variant text not null default 'traditional',
  fen text not null default 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  pgn text not null default '',
  current_turn text not null default 'w' check (current_turn in ('w','b')),
  time_control_minutes integer not null default 10 check (time_control_minutes between 1 and 180),
  increment_seconds integer not null default 0 check (increment_seconds between 0 and 60),
  white_time_ms bigint,
  black_time_ms bigint,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (black_id is null or black_id <> white_id)
);

create table public.game_moves (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  ply integer not null check (ply > 0),
  from_square text not null check (from_square ~ '^[a-h][1-8]$'),
  to_square text not null check (to_square ~ '^[a-h][1-8]$'),
  promotion text check (promotion is null or promotion in ('q','r','b','n')),
  san text not null,
  fen_after text not null,
  created_at timestamptz not null default now(),
  unique (game_id, ply)
);

create index games_status_created_idx on public.games(status, created_at desc);
create index game_moves_game_ply_idx on public.game_moves(game_id, ply);

alter table public.profiles enable row level security;
alter table public.games enable row level security;
alter table public.game_moves enable row level security;

create policy "profiles are readable"
on public.profiles for select
using (true);

create policy "users update own profile"
on public.profiles for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "authenticated users can create waiting games"
on public.games for insert to authenticated
with check (white_id = auth.uid() and black_id is null and status = 'waiting');

create policy "users can read open or participating games"
on public.games for select to authenticated
using (status = 'waiting' or white_id = auth.uid() or black_id = auth.uid());

create policy "participants can update games"
on public.games for update to authenticated
using (white_id = auth.uid() or black_id = auth.uid())
with check (white_id = auth.uid() or black_id = auth.uid());

create policy "participants can read moves"
on public.game_moves for select to authenticated
using (
  exists (
    select 1 from public.games g
    where g.id = game_moves.game_id
      and (g.white_id = auth.uid() or g.black_id = auth.uid())
  )
);

create policy "participants can insert own moves"
on public.game_moves for insert to authenticated
with check (
  player_id = auth.uid()
  and exists (
    select 1 from public.games g
    where g.id = game_moves.game_id
      and (g.white_id = auth.uid() or g.black_id = auth.uid())
  )
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  desired_username text;
  final_username text;
begin
  desired_username := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'username'), ''),
    split_part(new.email, '@', 1),
    'player'
  );

  final_username := left(desired_username, 20);

  if exists(select 1 from public.profiles where username = final_username) then
    final_username := left(desired_username, 15) || '-' || substr(new.id::text, 1, 4);
  end if;

  insert into public.profiles (id, username)
  values (new.id, final_username);

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.join_waiting_game(target_game_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  joined_id uuid;
begin
  update public.games
  set
    black_id = auth.uid(),
    status = 'active',
    started_at = now(),
    updated_at = now()
  where id = target_game_id
    and status = 'waiting'
    and black_id is null
    and white_id <> auth.uid()
  returning id into joined_id;

  if joined_id is null then
    raise exception 'Game is no longer available';
  end if;

  return joined_id;
end;
$$;

revoke all on function public.join_waiting_game(uuid) from public;
grant execute on function public.join_waiting_game(uuid) to authenticated;

alter publication supabase_realtime add table public.games;
alter publication supabase_realtime add table public.game_moves;
