create extension if not exists pgcrypto;

create type public.game_status as enum ('waiting', 'active', 'completed', 'cancelled');
create type public.game_result as enum ('white', 'black', 'draw');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) between 3 and 24),
  rating integer not null default 1200 check (rating >= 0),
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  draws integer not null default 0 check (draws >= 0),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.games (
  id uuid primary key default gen_random_uuid(),
  white_id uuid not null references public.profiles(id) on delete cascade,
  black_id uuid references public.profiles(id) on delete set null,
  status public.game_status not null default 'waiting',
  result public.game_result,
  variant text not null default 'traditional',
  fen text not null default 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
  pgn text not null default '',
  current_turn text not null default 'w' check (current_turn in ('w','b')),
  time_control_minutes integer not null default 10 check (time_control_minutes between 1 and 180),
  increment_seconds integer not null default 0 check (increment_seconds between 0 and 60),
  white_time_ms bigint,
  black_time_ms bigint,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (black_id is null or black_id <> white_id)
);

create table public.game_moves (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  ply integer not null check (ply > 0),
  from_square text not null check (from_square ~ '^[a-h][1-8]$'),
  to_square text not null check (to_square ~ '^[a-h][1-8]$'),
  promotion text check (promotion is null or promotion in ('q','r','b','n')),
  san text not null,
  fen_after text not null,
  created_at timestamptz not null default now(),
  unique (game_id, ply)
);

create index games_status_created_idx on public.games(status, created_at desc);
create index game_moves_game_ply_idx on public.game_moves(game_id, ply);

alter table public.profiles enable row level security;
alter table public.games enable row level security;
alter table public.game_moves enable row level security;

create policy "profiles are readable"
on public.profiles for select
using (true);

create policy "users can read open or participating games"
on public.games for select to authenticated
using (status = 'waiting' or white_id = auth.uid() or black_id = auth.uid());

create policy "participants can read moves"
on public.game_moves for select to authenticated
using (
  exists (
    select 1 from public.games g
    where g.id = game_moves.game_id
      and (g.white_id = auth.uid() or g.black_id = auth.uid())
  )
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  desired_username text;
  final_username text;
begin
  desired_username := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'username'), ''),
    split_part(new.email, '@', 1),
    'player'
  );

  final_username := left(desired_username, 20);

  if exists(select 1 from public.profiles where username = final_username) then
    final_username := left(desired_username, 15) || '-' || substr(new.id::text, 1, 4);
  end if;

  insert into public.profiles (id, username)
  values (new.id, final_username);

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.create_waiting_game(
  game_variant text default 'traditional',
  game_minutes integer default 10
)
returns uuid
language plpgsql
security definer
set search_path = public
as $
declare
  created_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if game_variant <> 'traditional' then
    raise exception 'Variant is not available for online play yet';
  end if;

  if game_minutes < 1 or game_minutes > 180 then
    raise exception 'Invalid time control';
  end if;

  insert into public.games (
    white_id,
    status,
    variant,
    time_control_minutes
  )
  values (
    auth.uid(),
    'waiting',
    game_variant,
    game_minutes
  )
  returning id into created_id;

  return created_id;
end;
$;

revoke all on function public.create_waiting_game(text, integer) from public;
grant execute on function public.create_waiting_game(text, integer) to authenticated;

create or replace function public.join_waiting_game(target_game_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  joined_id uuid;
begin
  update public.games
  set
    black_id = auth.uid(),
    status = 'active',
    started_at = now(),
    updated_at = now()
  where id = target_game_id
    and status = 'waiting'
    and black_id is null
    and white_id <> auth.uid()
  returning id into joined_id;

  if joined_id is null then
    raise exception 'Game is no longer available';
  end if;

  return joined_id;
end;
$$;

revoke all on function public.join_waiting_game(uuid) from public;
grant execute on function public.join_waiting_game(uuid) to authenticated;

alter publication supabase_realtime add table public.games;
alter publication supabase_realtime add table public.game_moves;


-- Casual online move submission.
-- Chess legality is checked in the browser for this MVP. This function still
-- enforces participation, turn ownership, sequencing, and atomic persistence.
-- Rated play must remain disabled until move legality is independently
-- validated by trusted server-side code.
create or replace function public.submit_game_move(
  target_game_id uuid,
  move_from text,
  move_to text,
  move_promotion text,
  move_san text,
  next_fen text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  game_row public.games%rowtype;
  next_ply integer;
  caller_color text;
begin
  if move_from !~ '^[a-h][1-8]$' or move_to !~ '^[a-h][1-8]$' then
    raise exception 'Invalid square';
  end if;

  if move_promotion is not null and move_promotion not in ('q','r','b','n') then
    raise exception 'Invalid promotion';
  end if;

  select *
    into game_row
    from public.games
    where id = target_game_id
    for update;

  if not found then
    raise exception 'Game not found';
  end if;

  if game_row.status <> 'active' then
    raise exception 'Game is not active';
  end if;

  caller_color := case
    when game_row.white_id = auth.uid() then 'w'
    when game_row.black_id = auth.uid() then 'b'
    else null
  end;

  if caller_color is null then
    raise exception 'Not a participant';
  end if;

  if caller_color <> game_row.current_turn then
    raise exception 'Not your turn';
  end if;

  select coalesce(max(ply), 0) + 1
    into next_ply
    from public.game_moves
    where game_id = target_game_id;

  insert into public.game_moves (
    game_id,
    player_id,
    ply,
    from_square,
    to_square,
    promotion,
    san,
    fen_after
  )
  values (
    target_game_id,
    auth.uid(),
    next_ply,
    move_from,
    move_to,
    nullif(move_promotion, ''),
    move_san,
    next_fen
  );

  update public.games
  set
    fen = next_fen,
    current_turn = case when game_row.current_turn = 'w' then 'b' else 'w' end,
    updated_at = now()
  where id = target_game_id;

  return next_ply;
end;
$$;

revoke all on function public.submit_game_move(uuid, text, text, text, text, text) from public;
grant execute on function public.submit_game_move(uuid, text, text, text, text, text) to authenticated;
