-- Beta-readiness backend:
-- - preserve completed game history when an account is deleted
-- - collect signed-in beta feedback with owner-scoped RLS
-- - reuse an existing waiting table and prevent one player from flooding the lobby

alter table public.games
  alter column white_id drop not null;

alter table public.game_moves
  alter column player_id drop not null;

alter table public.games
  drop constraint if exists games_white_id_fkey;
alter table public.games
  add constraint games_white_id_fkey
  foreign key (white_id) references public.profiles(id) on delete set null;

alter table public.game_moves
  drop constraint if exists game_moves_player_id_fkey;
alter table public.game_moves
  add constraint game_moves_player_id_fkey
  foreign key (player_id) references public.profiles(id) on delete set null;

create table if not exists public.beta_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  category text not null check (category in ('bug','idea','confusing','other')),
  message text not null check (char_length(message) between 10 and 2000),
  app_view text,
  user_agent text,
  status text not null default 'new' check (status in ('new','reviewed','resolved')),
  created_at timestamptz not null default now()
);

create index if not exists beta_feedback_user_created_idx
  on public.beta_feedback(user_id, created_at desc);

alter table public.beta_feedback enable row level security;

revoke all on table public.beta_feedback from anon, authenticated;
grant insert on table public.beta_feedback to authenticated;

drop policy if exists "users submit own beta feedback" on public.beta_feedback;
create policy "users submit own beta feedback"
on public.beta_feedback
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create or replace function public.create_waiting_game_service(
  actor_id uuid,
  game_variant text default 'traditional',
  game_minutes integer default 10
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  created_id uuid;
  existing_id uuid;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  if not exists(select 1 from public.profiles where id = actor_id) then
    raise exception 'Player profile not found';
  end if;

  if game_variant <> 'traditional' then
    raise exception 'Variant is not available for online play yet';
  end if;

  if game_minutes < 0 or game_minutes > 180 then
    raise exception 'Invalid time control';
  end if;

  select id into existing_id
  from public.games
  where white_id = actor_id
    and status = 'waiting'
  order by created_at desc
  limit 1;

  if existing_id is not null then
    return existing_id;
  end if;

  if exists(
    select 1
    from public.games
    where status = 'active'
      and (white_id = actor_id or black_id = actor_id)
  ) then
    raise exception 'Resume or finish your active game before creating another';
  end if;

  insert into public.games (
    white_id,
    status,
    variant,
    fen,
    current_turn,
    time_control_minutes,
    increment_seconds,
    white_time_ms,
    black_time_ms
  )
  values (
    actor_id,
    'waiting',
    game_variant,
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 0 1',
    'b',
    game_minutes,
    0,
    case when game_minutes = 0 then 0 else game_minutes::bigint * 60000 end,
    case when game_minutes = 0 then 0 else game_minutes::bigint * 60000 end
  )
  returning id into created_id;

  return created_id;
end;
$$;

revoke all on function public.create_waiting_game_service(uuid, text, integer)
  from public, anon, authenticated;
grant execute on function public.create_waiting_game_service(uuid, text, integer)
  to service_role;

create or replace function public.join_waiting_game_service(
  target_game_id uuid,
  actor_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  joined_id uuid;
begin
  if actor_id is null then
    raise exception 'Authentication required';
  end if;

  if not exists(select 1 from public.profiles where id = actor_id) then
    raise exception 'Player profile not found';
  end if;

  if exists(
    select 1
    from public.games
    where status in ('waiting','active')
      and (white_id = actor_id or black_id = actor_id)
  ) then
    raise exception 'Resume or finish your current game before joining another';
  end if;

  update public.games
  set
    black_id = actor_id,
    status = 'active',
    current_turn = 'b',
    started_at = now(),
    last_move_at = now(),
    white_time_ms = case when time_control_minutes = 0 then 0 else time_control_minutes::bigint * 60000 end,
    black_time_ms = case when time_control_minutes = 0 then 0 else time_control_minutes::bigint * 60000 end,
    updated_at = now()
  where id = target_game_id
    and status = 'waiting'
    and black_id is null
    and white_id is not null
    and white_id <> actor_id
  returning id into joined_id;

  if joined_id is null then
    raise exception 'Game is no longer available';
  end if;

  return joined_id;
end;
$$;

revoke all on function public.join_waiting_game_service(uuid, uuid)
  from public, anon, authenticated;
grant execute on function public.join_waiting_game_service(uuid, uuid)
  to service_role;
